### ISSUE TITLE
firmware: populate all GPIO aliases based on current states of module PCBs

### ISSUE THREAD

**Issue by vkottler** [badgerloop-software/pod3#3]
Pin usage on each nucleo32 is in a stable state and as a result the pins can all be initialized properly during boot.

This should be completed before work on driver development and driver calling code is started

**Comment by vkottler** [comment]
@ethanlink17 when I finish #1 would you want to do this?

Basically we can use the `GPIO` struct to automatically initialize GPIO pins at boot.

Right now this is done in [`pin_alias.c`](https://github.com/badgerloop-software/pod/blob/master/embedded/common/pin_alias.c)

**Comment by vkottler** [comment]
Example of how to add an entry (from [common/board.c](https://github.com/badgerloop-software/pod/blob/embedded-setup/embedded/common/board.c)):

```
/* Nucleo 32 I/O */
FILL_GPIO(LED,      GPIOB, 3, OUTPUT, LOW_SPEED, NONE, true, LED)
FILL_AFIO(UART_TX,  GPIOA, 2, ALT, 7, MEDIUM_SPEED, NONE, true, OTHER)
FILL_AFIO(UART_RX,  GPIOA, 15, ALT, 3, MEDIUM_SPEED, NONE, true, OTHER)
```

`common/board.c` is a good location to put this code because it will be the same for every module / board (and these entries can go anywhere in the code).

For module-specific code, the entries can go in the source files in the [app](https://github.com/badgerloop-software/pod/tree/embedded-setup/embedded/app) directory.

Also keep in mind `FILL_GPIO` and `FILL_AFIO` are different, with the only difference being `FILL_GPIO` doesn't require a value for the alternate function register fields.

**Comment by vkottler** [comment]
For a more low-level understanding of how this works, check out [include/pin_alias.h](https://github.com/badgerloop-software/pod/blob/embedded-setup/embedded/include/pin_alias.h):

```
#define FILL_AFIO(_name, _port, _pin, _mode, _af_val, _speed, _pullup, _usable, _group) \
     const GPIO __attribute__((section (".GPIO"))) _name##_pin = {\
        .name = #_name,\
        .port = _port,\
        .pin = _pin,\
        .mode = _mode,\
        .speed = _speed,\
        .pullup = _pullup,\
        .usable = _usable,\
        .af_val = _af_val,\
        .group = _group\
    };

#define FILL_GPIO(_name, _port, _pin, _mode, _speed, _pullup, _usable, _group) \
    FILL_AFIO(_name, _port, _pin, _mode, 0, _speed, _pullup, _usable, _group)

extern unsigned int __GPIO_ENTRIES_END, __GPIO_ENTRIES_START;
#define NUM_GPIO_ALIAS (\
    (((unsigned int) &__GPIO_ENTRIES_END - (unsigned int) &__GPIO_ENTRIES_START)/sizeof(GPIO))\
)
```

From [common/pin_alias.c](https://github.com/badgerloop-software/pod/blob/embedded-setup/embedded/common/pin_alias.c):

```
const char *GROUP_NAMES[] = {
    "OTHER", "SENSOR", "VALVE", "RETRO", "LED", "I2C", "PRESSURE"
};
const uint8_t NUM_GROUPS = sizeof(GROUP_NAMES) / sizeof(char *);

const GPIO *GPIO_TABLE = (GPIO *) &__GPIO_ENTRIES_START;
```

From [proc/link.ld](https://github.com/badgerloop-software/pod/blob/embedded-setup/embedded/proc/link.ld):

```
/* GPIO initialization data section */
__GPIO_ENTRIES_START = .;
KEEP(*(.GPIO))
__GPIO_ENTRIES_END = .;
```

**Comment by vkottler** [comment]
This appears to be complete, just needs to be double-checked by @rcastle1 and I

**Comment by rcastle1** [comment]
Looks good. I'll work on getting a functional description of the each solenoid, LED, etc.

**Comment by rcastle1** [comment]
Updated to latest board revision. Need to add i2c gpio next

**Comment by rcastle1** [comment]
Added I2C information. Closing ticket. Re-open if major pinout changes occur.
