### ISSUE TITLE
Dashboard: Embedded Terminal Won't Use Nodejs

### ISSUE THREAD

**Issue by ezraboley** [badgerloop-software/pod3#6]
The main terminal works, however the terminal on the front page can't use things like 'require()' which are needed if it's going to have the functionality we need.

**Comment by vkottler** [comment]
Having trouble understanding what this means. Can you elaborate?

**Comment by ezraboley** [comment]
Sorry yeah, I think it could have to do with the fact that it's in an iframe, but accessing parts of node (like built in libraries) fails on the front page. This could be solved by changing how its implemented but something needs to be changed

**Comment by vkottler** [comment]
Node is a server-side scripting language, it will never run as front-end JavaScript.

There should be no need to call server-side code in the front-end, there should only be a need to retrieve data via API call and render it.

The console should operate the same way. It only needs to send something out once the user has hit enter and it can either continuously poll for new input to render or wait a certain amount of time after sending something out to try and load new text to render
