### ISSUE TITLE
MongoDB on a 32 bit OS

### ISSUE THREAD

**Issue by ezraboley** [badgerloop-software/pod3#7]
We need to figure out how to get it set up on a raspberry pi or an equivalent 32 bit OS.

**Comment by vkottler** [comment]
Should we just use something else?

**Comment by ezraboley** [comment]
I'd say so, but then the issue is changed to research potential databases

**Comment by vkottler** [comment]
Probably we should just use MySQL. I have some existing assets to get started with a basic telemetry schema that we can add to here: [badgerloop-software/dashboard/database](https://github.com/badgerloop-software/dashboard/tree/master/database)
